# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='people',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
