# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170911_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='middlename',
            field=models.CharField(default='', max_length=100),
        ),
    ]
