# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20170911_0253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='middlename',
            new_name='middle_name',
        ),
    ]
